"""Unpacked Node.js fallback: extract, patch, and npm install."""

import json
import os
import shutil
import subprocess
import stat
from dataclasses import dataclass
from pathlib import Path

from cc_extractor.bun_extract import extract_all, parse_bun_binary
from cc_extractor._utils import atomic_write_text_no_symlink, utc_now as _utc_now

from .js_patch import PatchUnpackedResult, patch_unpacked_entry


RUNTIME_DEPENDENCIES = {
    "ws": "8.18.0",
    "node-fetch": "3.3.2",
    "undici": "7.0.0",
    "yaml": "2.6.0",
}
UNPACKED_SENTINEL = ".cc-extractor-unpacked"
NPM_PROJECT_METADATA = ("package-lock.json", "npm-shrinkwrap.json", ".npmrc")


class UnpackAndPatchError(Exception):
    def __init__(self, stage, message):
        self.stage = stage
        super().__init__(f"unpack-and-patch ({stage}): {message}")


@dataclass
class UnpackAndPatchInputs:
    pristine_binary_path: str
    unpacked_dir: str
    config: dict
    overlays: dict = None
    managed_root: str = None


@dataclass
class UnpackAndPatchResult:
    entry_path: str
    patch: PatchUnpackedResult


def unpack_and_patch(
    inputs=None,
    *,
    pristine_binary_path=None,
    unpacked_dir=None,
    config=None,
    overlays=None,
    managed_root=None,
):
    if inputs is not None:
        if isinstance(inputs, dict):
            inputs = UnpackAndPatchInputs(**inputs)
        pristine_binary_path = inputs.pristine_binary_path
        unpacked_dir = inputs.unpacked_dir
        config = inputs.config
        overlays = inputs.overlays
        managed_root = inputs.managed_root

    if pristine_binary_path is None or unpacked_dir is None:
        raise UnpackAndPatchError("extract", "pristine_binary_path and unpacked_dir are required")

    out_dir = Path(unpacked_dir)
    _prepare_unpacked_dir(out_dir, managed_root=Path(managed_root) if managed_root else None)

    try:
        data = Path(pristine_binary_path).read_bytes()
    except OSError as exc:
        raise UnpackAndPatchError("extract", f"read {pristine_binary_path}: {exc}") from exc

    try:
        info = parse_bun_binary(data)
    except Exception as exc:
        raise UnpackAndPatchError("extract", f"parse_bun_binary: {exc}") from exc

    try:
        extract_all(data, info, str(out_dir), manifest=True)
    except Exception as exc:
        raise UnpackAndPatchError("extract", str(exc)) from exc

    try:
        patch = patch_unpacked_entry(str(out_dir), config or {}, overlays)
    except Exception as exc:
        raise UnpackAndPatchError("patch", str(exc)) from exc

    _reset_npm_project_metadata(out_dir)
    _write_package_json(out_dir)
    _run_npm_install(out_dir)

    return UnpackAndPatchResult(entry_path=patch.entry_path, patch=patch)


def _write_package_json(unpacked_dir):
    pkg = {
        "name": "cc-extractor-unpacked",
        "version": "0.0.0",
        "private": True,
        "description": "Auto-generated by cc-extractor for runtime dependencies externalized by Bun.",
        "dependencies": RUNTIME_DEPENDENCIES,
    }
    atomic_write_text_no_symlink(Path(unpacked_dir) / "package.json", json.dumps(pkg, indent=2) + "\n")


def _reset_npm_project_metadata(unpacked_dir):
    root = Path(unpacked_dir)
    for name in NPM_PROJECT_METADATA:
        path = root / name
        try:
            if path.is_symlink() or path.is_file():
                path.unlink()
            elif path.is_dir():
                shutil.rmtree(path)
        except FileNotFoundError:
            continue


def _prepare_unpacked_dir(out_dir: Path, *, managed_root: Path = None) -> None:
    if out_dir.is_symlink():
        raise UnpackAndPatchError("extract", f"refusing symlink unpacked_dir: {out_dir}")
    if _is_protected_directory(out_dir):
        raise UnpackAndPatchError("extract", f"refusing dangerous unpacked_dir: {out_dir}")
    if out_dir.exists():
        if not out_dir.is_dir():
            raise UnpackAndPatchError("extract", f"unpacked_dir is not a directory: {out_dir}")
        sentinel = out_dir / UNPACKED_SENTINEL
        if not sentinel.exists():
            raise UnpackAndPatchError(
                "extract",
                f"refusing to remove unpacked_dir without {UNPACKED_SENTINEL}: {out_dir}",
            )
        _validate_generated_unpacked_dir(out_dir, managed_root)
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    _write_unpacked_metadata(out_dir)


def _write_unpacked_metadata(out_dir: Path) -> None:
    payload = {
        "tool": "cc-extractor",
        "kind": "unpacked-node-runtime",
        "path": str(out_dir.resolve()),
        "createdAt": _utc_now(),
    }
    atomic_write_text_no_symlink(
        out_dir / UNPACKED_SENTINEL,
        json.dumps(payload, indent=2, sort_keys=True) + "\n",
    )


def _validate_generated_unpacked_dir(out_dir: Path, managed_root: Path = None) -> None:
    if managed_root is None:
        raise UnpackAndPatchError(
            "extract",
            f"refusing automatic cleanup without managed root: {out_dir}",
        )
    if out_dir.is_symlink():
        raise UnpackAndPatchError("extract", f"refusing symlink unpacked_dir: {out_dir}")

    try:
        resolved_out = out_dir.resolve(strict=True)
        resolved_root = managed_root.resolve(strict=True)
    except OSError as exc:
        raise UnpackAndPatchError("extract", f"cannot resolve unpacked_dir: {exc}") from exc

    if resolved_out == resolved_root or resolved_root not in resolved_out.parents:
        raise UnpackAndPatchError(
            "extract",
            f"refusing to clean unpacked_dir outside managed root: {out_dir}",
        )
    _validate_unpacked_path_ownership(resolved_out, resolved_root)

    metadata_path = out_dir / UNPACKED_SENTINEL
    if metadata_path.is_symlink() or not metadata_path.is_file():
        raise UnpackAndPatchError("extract", f"refusing unsafe unpacked metadata: {metadata_path}")
    try:
        metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        raise UnpackAndPatchError("extract", f"invalid unpacked metadata: {metadata_path}: {exc}") from exc
    if (
        metadata.get("tool") != "cc-extractor"
        or metadata.get("kind") != "unpacked-node-runtime"
        or metadata.get("path") != str(resolved_out)
    ):
        raise UnpackAndPatchError("extract", f"unpacked metadata does not match directory: {out_dir}")


def _validate_unpacked_path_ownership(resolved_out: Path, resolved_root: Path) -> None:
    if os.name == "nt":
        return
    current_uid = os.getuid() if hasattr(os, "getuid") else None
    current = resolved_out
    while True:
        try:
            path_stat = current.stat()
        except OSError as exc:
            raise UnpackAndPatchError("extract", f"cannot inspect managed path: {current}: {exc}") from exc
        if current_uid is not None and path_stat.st_uid != current_uid:
            raise UnpackAndPatchError("extract", f"refusing managed path owned by another user: {current}")
        if path_stat.st_mode & stat.S_IWOTH:
            raise UnpackAndPatchError("extract", f"refusing world-writable managed path: {current}")
        if current == resolved_root:
            break
        current = current.parent


def _is_protected_directory(path: Path) -> bool:
    try:
        resolved = path.resolve()
    except OSError:
        return True
    protected = {Path("/").resolve(), Path.cwd().resolve()}
    if os.name != "nt":
        try:
            protected.add(Path.home().resolve())
        except RuntimeError:
            pass
    return resolved in protected


def _run_npm_install(unpacked_dir):
    commands = [
        ["npm", "install", "--package-lock-only", "--ignore-scripts", "--omit=dev", "--no-audit", "--no-fund", "--silent"],
        ["npm", "ci", "--ignore-scripts", "--omit=dev", "--no-audit", "--no-fund", "--silent"],
    ]
    for args in commands:
        _run_npm_command(args, unpacked_dir)


def _run_npm_command(args, unpacked_dir):
    try:
        result = subprocess.run(
            args,
            cwd=str(unpacked_dir),
            capture_output=True,
            text=True,
            check=False,
        )
    except OSError as exc:
        raise UnpackAndPatchError("deps", f"{' '.join(args)} failed to launch: {exc}") from exc

    if result.returncode != 0:
        detail = (result.stderr or result.stdout or f"exit {result.returncode}").strip()
        raise UnpackAndPatchError("deps", f"{' '.join(args)} exit {result.returncode}: {detail}")
